### ISSUE TITLE
Install Spring Cloud Data Flow in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-spring-cloud-dataflow#3]
## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105615787-42fe1e00-5da1-11eb-97a8-369110bd1f1a.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105615790-4abdc280-5da1-11eb-8cb1-1868e8ed2a78.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105616222-67f39080-5da3-11eb-965c-22b925b7d91d.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105616224-704bcb80-5da3-11eb-973d-a78f0e6c108a.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105616227-75a91600-5da3-11eb-853c-1f06c2f5dd88.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105616229-7b066080-5da3-11eb-85fc-e6d30a4fcf9b.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105616234-82c60500-5da3-11eb-9e5c-31747ebe9112.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105616296-f10ac780-5da3-11eb-9ed7-c02c3da1dfca.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105616309-f831d580-5da3-11eb-8284-397917ed62e0.PNG)

## Step 3: Install Spring Cloud Data Flow

* Click on the search section at the top of the main page, type Spring Cloud Data Flow, and click on it.

![spring1](https://user-images.githubusercontent.com/70336951/105616316-02ec6a80-5da4-11eb-9f48-f0bdbf365b06.PNG)

*  A new window opens, select the cluster and put the name you want to the workspace, in this case it will be called _spring-example_, accept the terms and click on install. You can modify the different installation parameters at the bottom, in our example we will leave them default, you can read more about the parameters [here](https://cloud.ibm.com/catalog/content/spring-cloud-dataflow "here").

![spring2](https://user-images.githubusercontent.com/70336951/105616544-e4876e80-5da5-11eb-9ca0-eb5fc964dbde.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105616549-eea96d00-5da5-11eb-9865-cb05f20a1995.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105616552-f406b780-5da5-11eb-8498-cd20be411b96.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105616756-2cf35c00-5da7-11eb-9367-f279f56375e4.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105616758-31b81000-5da7-11eb-8f08-431ac9fbcc9a.PNG)

* Once you have installed the terminal, click on the action button again, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *spring-example* is now active.

`$ kubectl get ns`

![testspring1](https://user-images.githubusercontent.com/70336951/105616767-38df1e00-5da7-11eb-86de-fc0d6fdda6d2.PNG)

* You can then obtain more data about the service and it's pods. You can see the different pods Spring is using.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testspring2](https://user-images.githubusercontent.com/70336951/105616772-3da3d200-5da7-11eb-8adb-40b122943fe2.PNG)

`$ kubectl get service -n NAME SERVICE`

![testspring3](https://user-images.githubusercontent.com/70336951/105616777-4399b300-5da7-11eb-9fb8-212bc178acdb.PNG)

* Select the pod within your service using bash if you want to use its files or change any configuration of it.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![testspring4](https://user-images.githubusercontent.com/70336951/105616780-498f9400-5da7-11eb-8101-231b13cedcad.PNG)

You have finished the installation, enjoy!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as "Closed" so it can be used by other users looking for information as if it were documentation
